/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

function requirePublicEnv(value: string | undefined, name: string) {
  const trimmed = value?.trim();

  if (!trimmed) {
    throw new Error(`${name} is required. Set it in the Expo/EAS public environment before building WMatch.`);
  }

  return trimmed;
}

// Expo only inlines EXPO_PUBLIC_* values when they are accessed via direct dot notation.
export const projectId = requirePublicEnv(
  process.env.EXPO_PUBLIC_SUPABASE_PROJECT_ID,
  'EXPO_PUBLIC_SUPABASE_PROJECT_ID',
);

export const publicAnonKey = requirePublicEnv(
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
  'EXPO_PUBLIC_SUPABASE_ANON_KEY',
);
